### ISSUE TITLE
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)

### ISSUE THREAD

**Issue by DamienGR** [mattacosta/php-colordiff#3]
PHP 7.4 deprecates the unparenthesized ternary operator, see https://www.php.net/manual/en/migration74.deprecated.php
line 249 should be updated from : 
`$h = ($color['r'] == $max) ? $db - $dg : ($color['g'] == $max) ? (1.0 / 3.0) + $dr - $db : (2.0 / 3.0) + $dg - $dr;`
to : 
`$h = ($color['r'] == $max) ? $db - $dg : (($color['g'] == $max) ? (1.0 / 3.0) + $dr - $db : (2.0 / 3.0) + $dg - $dr);`

**Comment by mattacosta** [comment]
So upon review of this ancient code, I have opted to fix this and another bug in a new repo where I can refactor everything and add new features. As such, I'll be closing this as a won't fix, but thanks for reporting it.
